---
name: default

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # pre-commit
      - uses: actions/setup-python@v3
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install pre-commit

      # terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"

      # target
      - run: make check

      # sanity check
      - run: git diff --exit-code
        if: ${{ !env.ACT }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"

      # target
      - run: make install
      - run: make test

      # sanity check
      - run: git diff --exit-code
        if: ${{ !env.ACT }}
