---
name: default

"on":
  pull_request:
  push:
    branches:
      - master

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install pre-commit

      - uses: hashicorp/setup-terraform@v1
      - run: make tf-install

      - run: make check

      - run: git diff --exit-code
        if: ${{ !env.ACT }}

  test:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
      - run: make tf-install

      - run: make test

      - run: git diff --exit-code
        if: ${{ !env.ACT }}
